core/urls.py
import notifications
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include, re_path
from django.views.static import serve

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('s/', include('src.portals.customer.urls', namespace='customer')),
    path('c/', include('src.portals.company.urls', namespace='company')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

urlpatterns += [
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/accounts/urls.py
from django.urls import path
from .views import CrossAuthView, UserUpdateView, IdentificationCheckView

app_name = "accounts"
urlpatterns = [
    path('cross-auth/', CrossAuthView.as_view(), name='cross-auth-view'),
    path('user/change/', UserUpdateView.as_view(), name='user-change'),
    path('identification-check/', IdentificationCheckView.as_view(), name='identification-check'),
]

src/website/urls.py
# Django URL patterns for mapping views to specific URLs
from django.urls import path
from .views import HomeView, ProjectView, AboutView, ContactView, InternshipView, CompanyView, InternshipDetailsView, \
    CompanyDetailsView

app_name = 'website'
urlpatterns = [

    # URL pattern for the home page
    path('', HomeView.as_view(), name='home'),

    # URL pattern for the 'About' page
    path('about/', AboutView.as_view(), name='about'),

    # URL pattern for the 'Contact' page, handling both GET and POST requests
    path('contact/', ContactView.as_view(), name='contact'),

    # URL pattern for displaying a list of internship jobs
    path('internship/', InternshipView.as_view(), name='internship'),

    # URL pattern for displaying details of a specific internship job, using slug as a parameter
    path('internship/details/<slug:pk>', InternshipDetailsView.as_view(), name='internship-details'),

    # URL pattern for displaying a list of companies
    path('company/', CompanyView.as_view(), name='company'),

    # URL pattern for displaying details of a specific company, using slug as a parameter
    path('company/details/<slug:pk>', CompanyDetailsView.as_view(), name='company-details'),

    # URL pattern for displaying details of a specific project, using int as a parameter
    path('project/<int:pk>/', ProjectView.as_view(), name='project-detail'),

]

src/website/models.py
from django.core.exceptions import ValidationError
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Model for storing application details
class Application(models.Model):
    name = models.CharField(max_length=100, help_text='Application name', default='Intern Ease')
    short_name = models.CharField(max_length=10, help_text='Your application short name', default='EE')
    tagline = models.CharField(
        max_length=100, help_text='Your application business line', default='Empowering Futures through Collaboration'
    )
    description = models.TextField(
        default="Connect companies offering enriching internships with aspiring students seeking valuable experiences",
        help_text='Application description'
    )

    favicon = models.ImageField(
        upload_to='core/application/images', null=True, blank=True, help_text='Application favicon'
    )
    logo = models.ImageField(
        upload_to='core/application/images', null=True, blank=True,
        help_text='Application real colors logo'
    )
    logo_dark = models.ImageField(
        upload_to='core/application/images', null=True, blank=True, help_text='For dark theme only'
    )
    logo_light = models.ImageField(
        upload_to='core/application/images', null=True, blank=True, help_text='For light theme only'
    )

    contact_email1 = models.EmailField(
        max_length=100, default='support@internease.com', help_text='Application contact email 1'
    )
    contact_email2 = models.EmailField(
        max_length=100, default='support@internease.com', help_text='Application contact email 2'
    )
    contact_phone1 = PhoneNumberField(
        help_text='Application contact phone 1', default='+10000000000'
    )
    contact_phone2 = PhoneNumberField(
        help_text='Application contact phone 2', default='+10000000000'
    )

    address = models.CharField(
        max_length=255, help_text='Office address', default='XYZ, City, Country'
    )
    latitude = models.DecimalField(max_digits=10, decimal_places=6, help_text='Latitude', default=23.7)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, help_text='Longitude', default=90.3)

    terms_url = models.URLField(
        max_length=255, default='https://internease.com/terms-of-use/', help_text='Terms and Conditions page link'
    )

    version = models.CharField(max_length=10, help_text='Current version', default='1.0.0')
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Application"
        ordering = ['name']

    def __str__(self):
        return self.name

    # Validate only one record exists
    def clean_fields(self, exclude=None):
        if Application.objects.exists() and not self.pk:
            raise ValidationError("Only one record allowed.")
        super(Application, self).clean_fields(exclude=exclude)


# Model for storing contact details
class Contact(models.Model):
    name = models.CharField(max_length=100, help_text='Contact name')
    email = models.EmailField(max_length=100, help_text='Contact email')
    message = models.TextField(help_text='Contact message')
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Contact"
        ordering = ['name']

    def __str__(self):
        return self.name

src/website/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Your Name'
        self.fields['name'].widget.attrs['class'] = 'form-input border border-slate-100 dark:border-slate-800 mt-2'

        self.fields['email'].widget.attrs['placeholder'] = 'Your Email'
        self.fields['email'].widget.attrs['class'] = 'form-input border border-slate-100 dark:border-slate-800 mt-2'

        self.fields['message'].widget.attrs['placeholder'] = 'Your Message'
        self.fields['message'].widget.attrs['class'] = 'form-input border border-slate-100 dark:border-slate-800 mt-2'

src/website/views.py
from django.contrib import messages
from django.db.models import Q
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView

from src.portals.company.models import Job, Company, Review
from src.website.filters import CompanyFilter, InternshipFilter
from src.website.forms import ContactForm

from django.shortcuts import render


# Class for handling the home page view, displaying a list of internships with various filters
class HomeView(ListView):
    model = Job
    template_name = 'website/home.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['companies'] = Company.objects.all()[:5]
        kwargs['object_list'] = Job.objects.filter(job_type='internship')[:5]
        return super().get_context_data(**kwargs)


# Class for displaying the 'About' page
class AboutView(TemplateView):
    template_name = 'website/about.html'


# Class for handling the 'Contact' page, with GET and POST methods for form submission
class ContactView(View):
    form = ContactForm
    template_name = 'website/contact.html'

    def get(self, request):
        # Render the contact form
        return render(request, self.template_name, {'form': self.form})

    def post(self, request):
        # Process form submission and display success or error messages
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been sent successfully.')
        return render(request, self.template_name, {'form': self.form}) if form.is_valid() else render(request,
                                                                                                       self.template_name,
                                                                                                       {'form': form})


# Class for displaying a list of internship jobs
class InternshipView(ListView):
    model = Job
    template_name = 'website/internship.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        filter_form = InternshipFilter(self.request.GET, queryset=self.get_queryset())
        context['object_list'] = filter_form.qs
        context['form'] = filter_form.form
        print(filter_form.form)
        return context


# Class for displaying details of a specific internship job
class InternshipDetailsView(DetailView):
    model = Job
    template_name = 'website/internship_details.html'

    def get_context_data(self, **kwargs):
        # Add additional context data for displaying related internships
        context = super().get_context_data()
        context['internships'] = Job.objects.filter(status='o', company=self.object.company)[:3]
        context['reviews'] = Review.objects.filter(job=self.object)
        return context


# Class for displaying a list of companies
class CompanyView(ListView):
    model = Company
    template_name = 'website/company.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        filter_form = CompanyFilter(self.request.GET, queryset=self.get_queryset())
        context['object_list'] = filter_form.qs
        context['form'] = filter_form.form
        print(filter_form.form)
        return context


# Class for displaying details of a specific company
class CompanyDetailsView(DetailView):
    model = Company
    template_name = 'website/company_details.html'

    def get_context_data(self, **kwargs):
        # Add additional context data for displaying related companies
        context = super().get_context_data()
        context['internships'] = Job.objects.filter(company=self.object)[:3]

        return context


# Class for displaying details of a specific project
class ProjectView(DetailView):
    model = Job
    template_name = 'website/project_detail.html'
    context_object_name = 'object'

    def get_queryset(self):
        # Specify the queryset for retrieving project details along with related company information
        return Job.objects.select_related('company').all()

src/website/templates/website/include/footer.html
{% load static %}
{% load custom_tags %}


<footer class="relative bg-slate-900 dark:bg-slate-800">
    <div class="container">
        <div class="grid grid-cols-1">
            <div class="relative py-12">
                <div class="relative w-full">
                    <div class="grid md:grid-cols-12 grid-cols-1 gap-[30px]">

                        <div class="md:col-span-3">
                            <a href="/" class="flex justify-center md:justify-start focus:outline-none">
                                <img src="{% static 'images/logo.png' %}" style="height:100px;" class="" alt="">
                            </a>
                        </div>

                        <div class="md:col-span-9">
                            <ul class="list-disc footer-list ltr:md:text-right rtl:md:text-left text-center space-x-3">
                                <li class="inline-block">
                                    <a href="{% url 'website:home' %}"
                                       class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Home</a>
                                </li>
                                <li class="inline-block mt-[10px] md:mt-0">
                                    <a href="{% url 'accounts:cross-auth-view' %}"
                                       class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">
                                        Login
                                    </a>
                                </li>
                                <li class="inline-block mt-[10px] md:mt-0">
                                    <a href="{% url 'website:about' %}"
                                       class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">About
                                        us
                                    </a>
                                </li>
                                <li class="inline-block mt-[10px] md:mt-0">
                                    <a href="{% url 'website:contact' %}"
                                       class="text-gray-300 hover:text-gray-400 duration-500 ease-in-out font-medium">Contact
                                        us</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</footer>

src/website/templates/website/include/header.html
{% load custom_tags %}
{% load static %}

<!--WEBSITE------------------------------------------------------------------------------------------------------------>

<nav id="topnav" class="defaultscroll is-sticky nav-sticky">
    <div class="container">
        <a class="logo" href="/">
            <div class="block sm:hidden">

                <img src="{% static 'images/logo.png' %}" class="h-10 inline-block dark:hidden" alt="">
                <img src="{% static 'images/logo.png' %}" class="h-10 hidden dark:inline-block" alt="">
            </div>
            <div class="sm:block hidden">
                        <span class="inline-block dark:hidden">
                                <img src="{% static 'images/logo.png' %}" class="h-[24px] l-dark" alt="">
                                <img src="{% static 'images/logo.png' %}" class="h-[24px] l-light" alt="">
                        </span>
                <img src="{% static 'images/logo.png' %}" class="h-[24px] hidden dark:inline-block" alt="">
            </div>
        </a>

        <div class="menu-extras">
            <div class="menu-item">
                <a class="navbar-toggle" id="isToggle" onclick="toggleMenu()">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
            </div>
        </div>

        <div id="navigation">
            <ul class="navigation-menu justify-end nav-light">
                <li><a href="{% url 'website:home' %}" class="sub-menu-item">Home</a></li>
                <li><a href="{% url 'website:company' %}" class="sub-menu-item">Company</a></li>
                <li><a href="{% url 'website:internship' %}" class="sub-menu-item">Internships</a></li>
                <li><a href="{% url 'website:about' %}" class="sub-menu-item">About</a></li>
                <li><a href="{% url 'website:contact' %}" class="sub-menu-item">Contact</a></li>
                <li>
                    <a href="{% url 'accounts:cross-auth-view' %}" class="sub-menu-item">
                        {% if request.user.is_authenticated %}
                            Dashboard
                        {% else %}
                            Login
                        {% endif %}
                    </a>
                </li>
                {#                <li>#}
                {#                    <a href="{% url 'accounts:cross-auth-view' %}" class="sub-menu-item">#}
                {#                        {% if request.user.is_authenticated %}Dashboard{% else %}Login{% endif %}#}
                {#                    </a>#}
                {#                </li>#}
            </ul>
        </div>
    </div>
</nav>

src/website/templates/website/include/mini_code.html
<div class="fixed top-1/4 -left-2 z-50">
            <span class="relative inline-block rotate-90">
                <input type="checkbox" class="checkbox opacity-0 absolute" id="chk">
                <label class="label bg-slate-900 dark:bg-white shadow dark:shadow-gray-800 cursor-pointer rounded-full flex justify-between items-center p-1 w-14 h-8"
                       for="chk">
                    <i class="uil uil-moon text-[20px] text-yellow-500"></i>
                    <i class="uil uil-sun text-[20px] text-yellow-500"></i>
                    <span class="ball bg-white dark:bg-slate-900 rounded-full absolute top-[2px] left-[2px] w-7 h-7"></span>
                </label>
            </span>
</div>

<!-- Switcher -->

<!-- Back to top -->
<a href="#" onclick="topFunction()" id="back-to-top"
   class="back-to-top fixed hidden text-lg rounded-full z-10 bottom-5 end-5 h-9 w-9 text-center bg-emerald-600 text-white justify-center items-center"><i
        class="uil uil-arrow-up"></i></a>
<!-- Back to top -->