core/urls.py
import notifications
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include, re_path
from django.views.static import serve

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('s/', include('src.portals.customer.urls', namespace='customer')),
    path('c/', include('src.portals.company.urls', namespace='company')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

urlpatterns += [
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/portals/customer/urls.py
from django.urls import path
from .views import (
    DashboardView, MyReviewListView, ReviewCreateView, JobListView, ReviewListView
)

app_name = 'customer'
urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),
    path('my/reviews/', MyReviewListView.as_view(), name='my-review-list'),

    path('job/', JobListView.as_view(), name='job-list'),
    path('job/<int:pk>/review/create/', ReviewCreateView.as_view(), name='review-create'),
    path('job/<int:pk>/review/', ReviewListView.as_view(), name='review-list'),
]

src/portals/company/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models

from src.accounts.models import User, Country, Category, City


class Company(models.Model):
    BUSINESS_TYPE = (
        ('non profit', 'Non Profit'),
        ('government', 'Government'),
        ('small business', 'Small Business'),
        ('medium business', 'Medium Business'),
        ('enterprise', 'Enterprise'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default="Name")
    tag_line = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    business_type = models.CharField(
        max_length=255, choices=BUSINESS_TYPE, default='small business', verbose_name='Company Type'
    )

    logo = models.ImageField(upload_to='company_logo', null=True, blank=True)
    company_registration_no = models.CharField(max_length=255, null=True, blank=True)
    company_start_date = models.DateTimeField(verbose_name='Date started', null=True, blank=True)

    contact_number = models.CharField(max_length=20, null=True, blank=True, verbose_name='Phone')
    contact_email = models.CharField(max_length=255, null=True, blank=True, verbose_name='Email')
    company_address = models.TextField(null=True, blank=True, verbose_name='Address')

    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=False)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name


# MODEL JOBS
class Job(models.Model):
    STATUS_CHOICE = (
        ('open', 'Open'),
        ('close', 'Close')
    )
    JOB_TYPE = (
        ('full time', 'Full Time'),
        ('part time', 'Part Time'),
        ('remote', 'Remote'),
        ('freelance', 'Freelance'),
        ('internship', 'Internship'),
    )

    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    vacancy = models.IntegerField(default=0)
    description = models.TextField()
    detailed_description = models.TextField(null=True, blank=True)
    company = models.ForeignKey('Company', related_name='job_provider', on_delete=models.CASCADE, blank=True)
    logo = models.ImageField(upload_to='company_logo', null=True, blank=True)
    start_time = models.DateTimeField(null=True, blank=False)
    end_time = models.DateTimeField(null=True, blank=False)
    reviews = models.ManyToManyField(User, related_name='likes', through='company.Review')
    candidates = models.ManyToManyField(User, related_name='candidates', through='Candidate')
    status = models.CharField(max_length=5, choices=STATUS_CHOICE, default='open')

    job_type = models.CharField(max_length=50, null=True, blank=True, default='internship', choices=JOB_TYPE)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=False)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        ordering = ['-pk']
        verbose_name = "InternShip"
        verbose_name_plural = "InternShips"

    def __str__(self):
        return self.title

    def clean(self):
        if self.start_time and self.end_time and self.start_time >= self.end_time:
            raise ValidationError("End date must be greater than the start date.")
        return super().clean()

    def average_rating(self):
        reviews = Review.objects.filter(job=self)
        if reviews:
            rating_map = {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5}

            ratings = [rating_map[review.rating] for review in reviews]
            return sum(ratings) / len(ratings)
        return 0


class Review(models.Model):

    RATING_CHOICE = (
        ('1', '1 star'),
        ('2', '2 stars'),
        ('3', '3 stars'),
        ('4', '4 stars'),
        ('5', '5 stars'),
    )

    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    rating = models.CharField(max_length=1, default=RATING_CHOICE[3][0], choices=RATING_CHOICE)
    description = models.TextField(null=True, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


# CANDIDATE
class Candidate(models.Model):
    STATUS_CHOICE = (
        ('acc', 'Accepted'),
        ('pen', 'Pending'),
        ('app', 'Applied'),
        ('rej', 'Rejected'),
    )
    DEGREE_CHOICES = (
        ('ssc', 'Matric'),
        ('hssc', 'F.sc'),
        ('bs', 'Bachelors'),
        ('ms', 'Master'),
        ('phd', 'Doctorate'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    degree = models.CharField(
        max_length=15,
        choices=DEGREE_CHOICES,
        default='ssc',
        help_text="Name of Field in which you have passed bachelors - Leave blank if you don't have bachelors degree"
    )
    experience = models.PositiveIntegerField(default=0, help_text="Years of working experience")
    about = models.TextField(
        null=True, blank=True,
        help_text='Say something about yourself, your love to hear you, briefly describe yourself, interests etc'
    )
    previous_company = models.CharField(max_length=255, null=True, blank=True, help_text="Leave blank if not")
    job = models.ForeignKey(Job, on_delete=models.CASCADE, blank=True)
    status = models.CharField(max_length=3, choices=STATUS_CHOICE, default='app')
    cv = models.FileField(upload_to='company/candidate/cvs/',null=True,blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job.title


# FEEDBACK
class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.company.name

src/portals/customer/views.py
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (
    TemplateView, CreateView, ListView,
)
from notifications.signals import notify

from src.accounts.decorators import customer_required
from src.accounts.models import City
from src.portals.company.bll import recommended_jobs_for_candidate
from src.portals.company.models import Candidate, Job, Review


# VERIFIED : TESTED
@method_decorator(customer_required, name='dispatch')
class DashboardView(TemplateView):
    template_name = 'customer/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['review_count'] = Review.objects.filter(user=self.request.user).count()
        context['jobs'] = recommended_jobs_for_candidate(self.request.user)

        # for job in Job.objects.all():
        #     job.city = City.objects.order_by('?').first()
        #     job.save()

        return context


@method_decorator(customer_required, name='dispatch')
class JobListView(ListView):
    model = Job
    template_name = 'customer/job_list.html'

    def get_queryset(self):
        return Job.objects.filter().exclude()


# VERIFIED : TESTED
@method_decorator(customer_required, name='dispatch')
class MyReviewListView(ListView):
    template_name = 'customer/my_review_list.html'

    def get_queryset(self):
        return Review.objects.filter(user=self.request.user)


# VERIFIED : TESTED
@method_decorator(customer_required, name='dispatch')
class ReviewCreateView(CreateView):
    template_name = 'customer/review_form.html'
    model = Review
    fields = ['rating', 'description']
    success_url = reverse_lazy('customer:job-list')

    def dispatch(self, request, *args, **kwargs):
        job = get_object_or_404(Job, pk=self.kwargs['pk'])

        if Review.objects.filter(user=request.user, job=job):
            messages.error(request, 'You have already added your review to this job.')
            return redirect('customer:job-list')

        return super(ReviewCreateView, self).dispatch(request)

    def form_valid(self, form):
        job = get_object_or_404(Job, pk=self.kwargs['pk'])
        form.instance.user = self.request.user
        form.instance.job = job

        return super(ReviewCreateView, self).form_valid(form)


@method_decorator(customer_required, name='dispatch')
class ReviewListView(ListView):
    template_name = 'customer/review_list.html'

    def get_queryset(self):
        job = get_object_or_404(Job, pk=self.kwargs['pk'])
        return Review.objects.filter(job=job)

    def get_context_data(self, **kwargs):
        context = super(ReviewListView, self).get_context_data(**kwargs)
        context['job'] = get_object_or_404(Job, pk=self.kwargs['pk'])
        return context

src/portals/customer/templates/customer/candidate_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Delete {{ object.job.title }}{% endblock %}

{% block content %}

    <div class="checkout-tabs">
        <form method="post">
            <div class="row">

                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">{% csrf_token %}
                                <p class="mb-2">Are you sure you want to leave this internship
                                    <b class="text-danger">"{{ object.job.title }}"</b>
                                    ?</p>
                                <input type="submit" class="btn btn-danger" value="Confirm">
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </form>
    </div>

{% endblock %}

src/portals/customer/templates/customer/candidate_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Apply/Update Application {% endblock %}

{% block content %}

    <div class="checkout-tabs">
            <div class="row justify-content-center">

                {# RIGHT #}
                <div class="col-xl-10 col-sm-9">
                    <form  method="POST" enctype="multipart/form-data">
                        <div class="card">
                            <div class="card-body">
                                <div class="tab-content" id="v-pills-tabContent">
                                    <div class="tab-pane fade active show" id="v-pills-payment" role="tabpanel"
                                         aria-labelledby="v-pills-payment-tab">
                                        <div>
                                            <h4 class="card-title">Personal information</h4>
                                            <p class="card-title-desc">Fill all information below</p>

                                            <div class="p-4 border">
                                                {% csrf_token %}
                                                {{form|crispy}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-sm-6">
                                <a href="{% url 'customer:application-list' %}"
                                   class="btn text-muted d-none d-sm-inline-block btn-link">
                                    <i class="mdi mdi-arrow-left mr-1"></i> My Applications </a>
                            </div>
                            <div class="col-sm-6">
                                <div class="text-sm-right">
                                    <button type="submit" class="btn btn-success">
                                        <i class="mdi mdi-check mr-1"></i> Apply
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
    </div>

{% endblock %}

src/portals/customer/templates/customer/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}


{% block base_title %} {{ request.user }} {% endblock %}
{% block base_links %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-10">
            <div class="card mini-stats-wid">
                <div class="card-body">
                    <div class="media">
                        <div class="mr-3 align-self-center">
                            <i class="fa fa-clipboard-list h1 text-dark mb-0"></i>
                        </div>
                        <div class="media-body">
                            <p class="text-muted mb-0">Welcome Back</p>
                            <h5 class="mb-0">
                                {{ request.user }}
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-2">
            <div class="card mini-stats-wid">
                <div class="card-body">
                    <div class="media">
                        <div class="mr-3 align-self-center">
                            <i class="fa fa-star h1 text-warning mb-0"></i>
                        </div>
                        <div class="media-body">
                            <p class="text-muted mb-0">Reviews</p>
                            <h5 class="mb-0">
                                {{ review_count }}
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="border-bottom card-body">
                    <p class="card-title mb-0">Recommended For You</p>
                </div>
                <div class="card-body p-0">
                    {% if jobs %}

                        <div class="table-responsive">
                            <table class="table table-centered table-nowrap table-hover">
                                <thead class="thead-light">
                                <tr>
                                    {% if not request.user.is_company %}
                                        <th scope="col"></th>
                                        <th scope="col">Company</th>
                                    {% endif %}
                                    <th scope="col">Title<br>Description</th>
                                    <th scope="col">Type <br> Category</th>
                                    <th scope="col">Location</th>
                                    <th scope="col">
                                        Start Date <br>
                                        Deadline
                                    </th>
                                    <th scope="col">Reviews</th>
                                    <th scope="col">Vacancies<br>Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in jobs %}
                                    <tr>
                                        {% if not request.user.is_company %}
                                            <td>
                                                <img src="https://placehold.co/100" alt="{{ object.company.name }}"
                                                     class="avatar-sm rounded-circle">
                                            </td>
                                            <td>
                                                <p class="mb-0">
                                                    <b><a href="#">{{ object.company.name }}</a></b>
                                                </p>
                                                <p class="mb-0 small"><i
                                                        class="fa fa-location-arrow"></i> {{ object.company.city|check_null }} {{ object.company.country }}
                                                </p>
                                            </td>
                                        {% endif %}
                                        <td>
                                            <p class="mb-0">
                                                <b><a href="#">{{ object.title }}</a></b>
                                            </p>
                                            <p class="mb-0 small">{{ object.description|truncatechars:60 }}</p>
                                        </td>
                                        <td>
                                            <p class="mb-0">
                                                <b>{{ object.job_type }}</b>
                                            </p>
                                            <p class="mb-0 small">{{ object.category }}</p>
                                        </td>
                                        <td>
                                            <p class="mb-0">
                                                <b>{{ object.city }}</b>
                                            </p>
                                            <p class="mb-0 small">{{ object.country }}</p>
                                        </td>
                                        <td>
                                            <i class="fa fa-clock"></i> {{ object.start_time.date }} <br>
                                            <i class="fa fa-clock text-danger"></i> {{ object.end_time.date }}
                                        </td>
                                        <td>
                                            <a href="

                                                    {% if request.user.is_company %}{% url 'company:review-list' object.pk %}{% else %}{% url 'customer:review-list' object.pk %}{% endif %}"
                                               class="text-secondary">
                                                <b class="h5">
                                                    <i class="fa fa-star text-warning"></i>
                                                    {{ object.average_rating }} ({{ object.reviews.count }})
                                                </b>
                                            </a>
                                        </td>
                                        <td>
                                            <b><i class="fa fa-chair"></i> {{ object.vacancy }}</b><br>

                                            {% if object.status == 'open' %}
                                                <b class="text-success">
                                                    <i class="fa fa-check-circle"></i> Open
                                                </b>
                                            {% else %}
                                                <b class="text-danger">
                                                    <i class="fa fa-times-circle"></i> Closed
                                                </b>
                                            {% endif %}

                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>

                    {% else %}
                        <p class="text-danger p-4">
                            <b><i class="fa fa-exclamation-circle"></i> No internships found.</b>
                        </p>
                    {% endif %}

                </div>
            </div>

        </div>
    </div>

{% endblock %}

src/portals/customer/templates/customer/job_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %} Recommended {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-body p-0 border">
                    {% if object_list %}

                        {% include 'company/include/job_list_div.html' %}

                    {% else %}
                        <p class="text-danger mb-0 p-4">
                            <b><i class="fa fa-exclamation-circle"></i> No internships found.</b>
                        </p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    {% if object_list %}
        <div class="row">
            <div class="col-md-12">
                <div class="mt-4">
                    <ul class="pagination">
                        {% if object_list.has_previous %}
                            <li>
                            <span>
                                <a href="{% relative_url object_list.previous_page_number 'page' request.GET.urlencode %}">
                                    Previous
                                </a>
                            </span>
                            </li>
                        {% endif %}
                        <li class="">
                            <span>Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.</span>
                        </li>
                        {% if object_list.has_next %}
                            <li>
                            <span>
                                <a href="{% relative_url object_list.next_page_number 'page' request.GET.urlencode %}">
                                    Next
                                </a>
                            </span>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

src/portals/customer/templates/customer/my_review_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %}
    Candidates
{% endblock %}


{% block content %}

    <div class="row mb-2">
        <div class="col-lg-12">
            <h4>Your reviews</h4>
            <hr>

            {% if object_list %}

                <div class="row">
                    {% for object in object_list %}

                        <div class="col-sm-3">
                            <div class="card">
                                <div class="card-body">

                                    <div class="text-center mb-3">
                                        <img src="{{ object.job.company.logo|image_or_placeholder:"100" }}" height="100"
                                             class="rounded-circle" alt="">
                                        <h6 class="font-size-15 mt-3 mb-1">{{ object.job.title }}</h6>
                                        <p class="mb-0 text-muted">
                                            {{ object.job.category }}
                                        </p>
                                        <a href="javascript: void(0);"
                                           class="badge text-white bg-primary font-size-11 m-1">
                                            {{ object.job.job_type }}
                                        </a>
                                    </div>
                                    <div class="text-center">
                                        <p class="text-muted">
                                            <b>{{ object.description }}</b>
                                        </p>
                                    </div>
                                    <div class="text-center h4">
                                        {{ object.rating|get_review_stars|safe }}
                                    </div>

                                </div>
                                <div class="card-body border-top">
                                    <div class="row">
                                        <div class="col-12 text-left">
                                            <i class="bx bxs-bank align-middle text-primary"></i> {{ object.job.company.name }}
                                        </div>
                                        <div class="col-12 text-left">
                                            <i class="bx bx-calendar align-middle text-primary"></i> {{ object.created_on }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>

            {% else %}
                <p class="text-danger mb-0">
                    <b>No reviews added yet.</b>
                </p>
            {% endif %}

        </div>

    </div>


{% endblock %}

src/portals/customer/templates/customer/review_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Apply/Update Application {% endblock %}

{% block content %}

    <div class="checkout-tabs">
        <div class="row justify-content-center">

            {# RIGHT #}
            <div class="col-xl-10 col-sm-9">
                <form method="POST" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            <div class="tab-content" id="v-pills-tabContent">
                                <div class="tab-pane fade active show" id="v-pills-payment" role="tabpanel"
                                     aria-labelledby="v-pills-payment-tab">
                                    <div>
                                        <h4 class="card-title">Personal information</h4>
                                        <p class="card-title-desc">Fill all information below</p>

                                        <div class="p-4 border">
                                            {% csrf_token %}
                                            {{ form|crispy }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row my-4">
                        <div class="col-sm-6">
                            <a href="{% url 'customer:job-list' %}"
                               class="btn text-muted d-none d-sm-inline-block btn-link">
                                <i class="mdi mdi-arrow-left mr-1"></i> My Reviews </a>
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-right">
                                <button type="submit" class="btn btn-success">
                                    <i class="mdi mdi-check mr-1"></i> Apply
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>

{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $("#id_rating").addClass('form-control');
        });
    </script>
{% endblock %}

src/portals/customer/templates/customer/review_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %}
    Candidates
{% endblock %}


{% block content %}

    <div class="row mb-2">
        <div class="col-lg-12">
            <a href="{% url 'customer:job-list' %}">
                <h5 class="mb-0 text-primary">
                    <i class="mdi mdi-arrow-left mr-1"></i> {{ job.title }}
                </h5>
            </a>
            <h4>Reviews preview</h4>
            <hr>

            {% if object_list %}

                {% include 'company/include/review_list_div.html' %}

            {% else %}
                <p class="text-danger mb-0">
                    <b>No reviews added yet.</b>
                </p>
            {% endif %}

        </div>

    </div>

{% endblock %}