core/urls.py
import notifications
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include, re_path
from django.views.static import serve

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('s/', include('src.portals.customer.urls', namespace='customer')),
    path('c/', include('src.portals.company.urls', namespace='company')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

urlpatterns += [
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/portals/company/urls.py
from django.urls import path
from .views import (
    JobUpdateView, JobListView, JobCreateView, JobDeleteView,
    DashboardView, CompanyUpdateView, ReviewListView
)

app_name = 'company'
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),

    path('company/', CompanyUpdateView.as_view(), name='company-update'),

    path('job/', JobListView.as_view(), name='job-list'),
    path('job/add/', JobCreateView.as_view(), name='job-add'),
    path('job/<int:pk>/change/', JobUpdateView.as_view(), name='job-update'),
    path('job/<int:pk>/delete/', JobDeleteView.as_view(), name='job-delete'),

    path('job/<int:pk>/review/', ReviewListView.as_view(), name='review-list'),

]

src/portals/company/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models

from src.accounts.models import User, Country, Category, City


class Company(models.Model):
    BUSINESS_TYPE = (
        ('non profit', 'Non Profit'),
        ('government', 'Government'),
        ('small business', 'Small Business'),
        ('medium business', 'Medium Business'),
        ('enterprise', 'Enterprise'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default="Name")
    tag_line = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    business_type = models.CharField(
        max_length=255, choices=BUSINESS_TYPE, default='small business', verbose_name='Company Type'
    )

    logo = models.ImageField(upload_to='company_logo', null=True, blank=True)
    company_registration_no = models.CharField(max_length=255, null=True, blank=True)
    company_start_date = models.DateTimeField(verbose_name='Date started', null=True, blank=True)

    contact_number = models.CharField(max_length=20, null=True, blank=True, verbose_name='Phone')
    contact_email = models.CharField(max_length=255, null=True, blank=True, verbose_name='Email')
    company_address = models.TextField(null=True, blank=True, verbose_name='Address')

    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=False)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name


# MODEL JOBS
class Job(models.Model):
    STATUS_CHOICE = (
        ('open', 'Open'),
        ('close', 'Close')
    )
    JOB_TYPE = (
        ('full time', 'Full Time'),
        ('part time', 'Part Time'),
        ('remote', 'Remote'),
        ('freelance', 'Freelance'),
        ('internship', 'Internship'),
    )

    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    vacancy = models.IntegerField(default=0)
    description = models.TextField()
    detailed_description = models.TextField(null=True, blank=True)
    company = models.ForeignKey('Company', related_name='job_provider', on_delete=models.CASCADE, blank=True)
    logo = models.ImageField(upload_to='company_logo', null=True, blank=True)
    start_time = models.DateTimeField(null=True, blank=False)
    end_time = models.DateTimeField(null=True, blank=False)
    reviews = models.ManyToManyField(User, related_name='likes', through='company.Review')
    candidates = models.ManyToManyField(User, related_name='candidates', through='Candidate')
    status = models.CharField(max_length=5, choices=STATUS_CHOICE, default='open')

    job_type = models.CharField(max_length=50, null=True, blank=True, default='internship', choices=JOB_TYPE)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=False)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        ordering = ['-pk']
        verbose_name = "InternShip"
        verbose_name_plural = "InternShips"

    def __str__(self):
        return self.title

    def clean(self):
        if self.start_time and self.end_time and self.start_time >= self.end_time:
            raise ValidationError("End date must be greater than the start date.")
        return super().clean()

    def average_rating(self):
        reviews = Review.objects.filter(job=self)
        if reviews:
            rating_map = {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5}

            ratings = [rating_map[review.rating] for review in reviews]
            return sum(ratings) / len(ratings)
        return 0


class Review(models.Model):

    RATING_CHOICE = (
        ('1', '1 star'),
        ('2', '2 stars'),
        ('3', '3 stars'),
        ('4', '4 stars'),
        ('5', '5 stars'),
    )

    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    rating = models.CharField(max_length=1, default=RATING_CHOICE[3][0], choices=RATING_CHOICE)
    description = models.TextField(null=True, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


# CANDIDATE
class Candidate(models.Model):
    STATUS_CHOICE = (
        ('acc', 'Accepted'),
        ('pen', 'Pending'),
        ('app', 'Applied'),
        ('rej', 'Rejected'),
    )
    DEGREE_CHOICES = (
        ('ssc', 'Matric'),
        ('hssc', 'F.sc'),
        ('bs', 'Bachelors'),
        ('ms', 'Master'),
        ('phd', 'Doctorate'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    degree = models.CharField(
        max_length=15,
        choices=DEGREE_CHOICES,
        default='ssc',
        help_text="Name of Field in which you have passed bachelors - Leave blank if you don't have bachelors degree"
    )
    experience = models.PositiveIntegerField(default=0, help_text="Years of working experience")
    about = models.TextField(
        null=True, blank=True,
        help_text='Say something about yourself, your love to hear you, briefly describe yourself, interests etc'
    )
    previous_company = models.CharField(max_length=255, null=True, blank=True, help_text="Leave blank if not")
    job = models.ForeignKey(Job, on_delete=models.CASCADE, blank=True)
    status = models.CharField(max_length=3, choices=STATUS_CHOICE, default='app')
    cv = models.FileField(upload_to='company/candidate/cvs/',null=True,blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job.title


# FEEDBACK
class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.company.name

src/portals/company/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import UpdateView, CreateView, DeleteView, ListView, TemplateView, DetailView
from src.accounts.decorators import company_required
from src.portals.company.bll import get_user_company_bll
from .models import Job, Company, Candidate, Review


# VERIFIED : TESTED
@method_decorator(company_required, name='dispatch')
class DashboardView(TemplateView):
    template_name = 'company/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        jobs = Job.objects.filter(company__user=self.request.user)

        context['jobs'] = jobs[:10]
        context['jobs_all_count'] = jobs.count()
        context['jobs_open_count'] = jobs.filter(status='open').count()
        context['jobs_close_count'] = jobs.filter(status='close').count()
        return context


# VERIFIED : TESTED
@method_decorator(company_required, name='dispatch')
class CompanyUpdateView(UpdateView):
    model = Company
    fields = [
        'name', 'business_type', 'tag_line', 'description', 'contact_number',
        'contact_email', 'company_address'
    ]

    def get_success_url(self):
        messages.success(self.request, 'Company Profile Updated Successfully.')
        return reverse_lazy('company:company-update')

    def get_object(self, queryset=None):
        return get_user_company_bll(self.request.user)


# VERIFIED : TESTED
@method_decorator(company_required, name='dispatch')
class JobListView(ListView):
    model = Job

    def get_queryset(self):
        return Job.objects.filter(company__user=self.request.user).exclude()


# VERIFIED : TESTED
@method_decorator(company_required, name='dispatch')
class JobCreateView(CreateView):
    model = Job
    fields = ['title', 'category', 'vacancy', 'description', 'city', 'country', 'start_time', 'end_time']
    success_url = reverse_lazy('company:job-list')

    def form_valid(self, form):
        form.instance.company = get_user_company_bll(self.request.user)
        return super(JobCreateView, self).form_valid(form)


# VERIFIED : TESTED
@method_decorator(company_required, name='dispatch')
class JobUpdateView(UpdateView):
    model = Job
    fields = ['title', 'category', 'vacancy', 'description', 'city', 'country', 'start_time', 'end_time']
    success_url = reverse_lazy('company:job-list')

    def get_object(self, queryset=None):
        return get_object_or_404(
            Job.objects.filter(
                company__user=self.request.user
            ), pk=self.kwargs['pk']
        )


# VERIFIED : TESTED
@method_decorator(company_required, name='dispatch')
class JobDeleteView(DeleteView):
    model = Job
    success_url = reverse_lazy('company:job-list')

    def get_object(self, queryset=None):
        return get_object_or_404(
            Job.objects.filter(
                company__user=self.request.user
            ), pk=self.kwargs['pk']
        )


# VERIFIED : TESTED
@method_decorator(company_required, name='dispatch')
class ReviewListView(ListView):

    def get_queryset(self):
        job = get_object_or_404(Job.objects.filter(company__user=self.request.user), pk=self.kwargs['pk'])
        return Review.objects.filter(job=job)

    def get_context_data(self, **kwargs):
        context = super(ReviewListView, self).get_context_data(**kwargs)
        context['job'] = get_object_or_404(Job.objects.filter(company__user=self.request.user), pk=self.kwargs['pk'])
        return context

src/portals/company/templates/company/company_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Company {% endblock %}

{% block content %}

    <div class="checkout-tabs">
        <form method="post">
            <div class="row justify-content-center">

                {# RIGHT #}
                <div class="col-sm-8">
                    <form action="" method="post">
                        <div class="card">
                            <div class="card-body border-bottom">
                                <h4 class="card-title mb-0">Company Profile</h4>
                            </div>
                            <div class="card-body p-5">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-success">
                                    <i class="mdi mdi-check mr-1"></i> Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </form>
    </div>

{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('#id_business_type').addClass('form-control');
        });
    </script>
{% endblock %}
```

src/portals/company/templates/company/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %} {{ request.user }} {% endblock %}
{% block base_links %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-4">
            <div class="card mini-stats-wid">
                <div class="card-body">
                    <div class="media">
                        <div class="mr-3 align-self-center">
                            <i class="bx bx-user-check h2 text-primary mb-0"></i>
                        </div>
                        <div class="media-body">
                            <p class="text-muted mb-2">Total internships</p>
                            <h5 class="mb-0">
                                {{ jobs_all_count }}
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card mini-stats-wid">
                <div class="card-body">
                    <div class="media">
                        <div class="mr-3 align-self-center">
                            <i class="bx bx-import h2 text-success mb-0"></i>
                        </div>
                        <div class="media-body">
                            <p class="text-muted mb-2">Opened</p>
                            <h5 class="mb-0">
                                {{ jobs_open_count }}
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card mini-stats-wid">
                <div class="card-body">
                    <div class="media">
                        <div class="mr-3 align-self-center">
                            <i class="bx bx-export h2 text-danger mb-0"></i>
                        </div>
                        <div class="media-body">
                            <p class="text-muted mb-2">Closed</p>
                            <h5 class="mb-0">
                                {{ jobs_close_count }}
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="border-bottom card-body">
                    <p class="card-title mb-0">Your internships</p>
                </div>
                <div class="card-body p-0">
                    {% if jobs %}

                        <div class="table-responsive">
                            <table class="table table-centered table-nowrap table-hover">
                                <thead class="thead-light">
                                <tr>
                                    {% if not request.user.is_company %}
                                        <th scope="col"></th>
                                        <th scope="col">Company</th>
                                    {% endif %}
                                    <th scope="col">Title<br>Description</th>
                                    <th scope="col">Type <br> Category</th>
                                    <th scope="col">Location</th>
                                    <th scope="col">
                                        Start Date <br>
                                        Deadline
                                    </th>
                                    <th scope="col">Reviews</th>
                                    <th scope="col">Vacancies<br>Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in jobs %}
                                    <tr>
                                        {% if not request.user.is_company %}
                                            <td>
                                                <img src="https://placehold.co/100" alt="{{ object.company.name }}"
                                                     class="avatar-sm rounded-circle">
                                            </td>
                                            <td>
                                                <p class="mb-0">
                                                    <b><a href="#">{{ object.company.name }}</a></b>
                                                </p>
                                                <p class="mb-0 small"><i
                                                        class="fa fa-location-arrow"></i> {{ object.company.city|check_null }} {{ object.company.country }}
                                                </p>
                                            </td>
                                        {% endif %}
                                        <td>
                                            <p class="mb-0">
                                                <b><a href="#">{{ object.title }}</a></b>
                                            </p>
                                            <p class="mb-0 small">{{ object.description|truncatechars:60 }}</p>
                                        </td>
                                        <td>
                                            <p class="mb-0">
                                                <b>{{ object.job_type }}</b>
                                            </p>
                                            <p class="mb-0 small">{{ object.category }}</p>
                                        </td>
                                        <td>
                                            <p class="mb-0">
                                                <b>{{ object.city }}</b>
                                            </p>
                                            <p class="mb-0 small">{{ object.country }}</p>
                                        </td>
                                        <td>
                                            <i class="fa fa-clock"></i> {{ object.start_time.date }} <br>
                                            <i class="fa fa-clock text-danger"></i> {{ object.end_time.date }}
                                        </td>
                                        <td>
                                            <a href="

                                                    {% if request.user.is_company %}{% url 'company:review-list' object.pk %}{% else %}{% url 'customer:review-list' object.pk %}{% endif %}"
                                               class="text-secondary">
                                                <b class="h5">
                                                    <i class="fa fa-star text-warning"></i>
                                                    {{ object.average_rating }} ({{ object.reviews.count }})
                                                </b>
                                            </a>
                                        </td>
                                        <td>
                                            <b><i class="fa fa-chair"></i> {{ object.vacancy }}</b><br>

                                            {% if object.status == 'open' %}
                                                <b class="text-success">
                                                    <i class="fa fa-check-circle"></i> Open
                                                </b>
                                            {% else %}
                                                <b class="text-danger">
                                                    <i class="fa fa-times-circle"></i> Closed
                                                </b>
                                            {% endif %}

                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>

                    {% else %}
                        <p class="text-danger p-4">
                            <b><i class="fa fa-exclamation-circle"></i> No internships found.</b>
                        </p>
                    {% endif %}

                </div>
            </div>

        </div>
    </div>

{% endblock %}

src/portals/company/templates/company/job_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Delete {{ object.title }} {% endblock %}

{% block content %}

            <div class="row justify-content-center">
                <div class="col-8">
                    <div class="card p-4">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <h1 class="text-danger">
                                    Remove <b class="text-danger">"{{ object.topic }}"</b>
                                </h1>
                                <h5 class="mb-4">
                                    Are you sure you want to delete this internship? This action cannot be undone.
                                </h5>
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-trash"></i> Remove
                                </button>
                            </form>
                        </div>
                    </div>
                </div>


            </div>

{% endblock %}

src/portals/company/templates/company/job_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} # {{ object.pk }} {% endblock %}

{% block page_heading %}

    {% if object.ticket_type.priority == 'h' %}
        <b class="p-2 bg-danger text-white"><i class="fa fa-exclamation-circle"></i> High</b>
    {% elif object.ticket_type.priority == 'm' %}
        <b class="p-2 bg-warning text-white"><i class="fa fa-exclamation-circle"></i> Medium</b>
    {% else %}
        <b class="p-2 bg-secondary text-white"><i class="fa fa-exclamation-circle"></i> Low</b>
    {% endif %}

    {% if object.is_completed %}
        <b class="p-2 bg-danger text-white"><i class="fa fa-door-closed"></i> Closed</b>
    {% else %}
        <b class="p-2 bg-success text-white"><i class="fa fa-door-open"></i> Open</b>
    {% endif %}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-8">

            <div class="card-body border-bottom">
                <p class="my-0 card-title">Ticket Information</p>
            </div>
            <div class="card-body">
                <p>
                    <b>
                        {{ object.description }}
                    </b>
                </p>
            </div>
            <div class="card-body border-top">
                <p class="mb-0"><i class="fa fa-calendar"></i> {{ object.created_on }}</p>
            </div>

        </div>
        <div class="col-4">

            {% if not object.is_completed %}
                <div class="card text-danger">
                    <div class="card-body border-bottom border-danger">
                        <p class="my-0 card-title">Current Status</p>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Make sure user queries/problem is resolved, if not please resolve user issue first then
                            close it
                        </p>
                        <a class="btn btn-danger" href="{% url 'admin-portal:ticket-status-change' object.pk %}">
                            <i class="fa fa-check-circle"></i> Close Ticket
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="card">
                    <div class="card-body border-bottom">
                        <p class="my-0 card-title">Current Status</p>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Case has been resolved and token has been closed, if you want to reopen issue please click
                            <b><a href="{% url 'admin-portal:ticket-status-change' object.pk %}">Here.</a></b>
                        </p>
                    </div>
                </div>
            {% endif %}

        </div>
    </div>

{% endblock %}

src/portals/company/templates/company/job_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Post internship {% endblock %}

{% block content %}

    <div class="checkout-tabs">
        <form method="post">
            <div class="row justify-content-center">

                {# RIGHT #}
                <div class="col-sm-8">
                    <form action="" method="post">
                        <div class="card">
                            <div class="card-body border-bottom">
                                <h4 class="card-title mb09">internship Form</h4>
                            </div>
                            <div class="card-body p-5">

                                {% csrf_token %}
                                {{ form|crispy }}

                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-check"></i> Submit
                                </button>

                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </form>
    </div>

{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('#id_category').addClass('form-control');
            $('#id_status').addClass('form-control');
            $('#id_city').addClass('form-control');
            $('#id_country').addClass('form-control');

            $('#id_start_time').attr('type', 'datetime-local');
            $('#id_end_time').attr('type', 'datetime-local');
        });
    </script>
{% endblock %}
```

src/portals/company/templates/company/job_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %} internships {% endblock %}

{% block content %}

    <div class="row mb-4 text-right">
        <div class="col-12">
            <a href="{% url 'company:job-add' %}" class="btn btn-primary">
                <i class="fa fa-plus"></i> Internships
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-body border p-0">
                    {% if object_list %}

                        {% include 'company/include/job_list_div.html' %}

                    {% else %}
                        <p class="text-danger mb-0 p-4">
                            <b><i class="fa fa-exclamation-circle"></i> No internships found.</b>
                        </p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    {% if object_list %}
        <div class="row">
            <div class="col-md-12">
                <div class="mt-4">
                    <ul class="pagination">
                        {% if object_list.has_previous %}
                            <li>
                            <span>
                                <a href="{% relative_url object_list.previous_page_number 'page' request.GET.urlencode %}">
                                    Previous
                                </a>
                            </span>
                            </li>
                        {% endif %}
                        <li class="">
                            <span>Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.</span>
                        </li>
                        {% if object_list.has_next %}
                            <li>
                            <span>
                                <a href="{% relative_url object_list.next_page_number 'page' request.GET.urlencode %}">
                                    Next
                                </a>
                            </span>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

src/portals/company/templates/company/review_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_title %}
    Candidates
{% endblock %}


{% block content %}

    <div class="row mb-2">
        <div class="col-lg-12">
            <a href="{% url 'company:job-list' %}">
                <h5 class="mb-0 text-primary">
                    <i class="mdi mdi-arrow-left mr-1"></i> {{ job.title }}
                </h5>
            </a>
            <h4>Reviews preview</h4>
            <hr>

            {% if object_list %}

                {% include 'company/include/review_list_div.html' %}

            {% else %}
                <p class="text-danger mb-0">
                    <b>No reviews added yet.</b>
                </p>
            {% endif %}

        </div>

    </div>

{% endblock %}