core/urls.py
import notifications
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include, re_path
from django.views.static import serve

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('s/', include('src.portals.customer.urls', namespace='customer')),
    path('c/', include('src.portals.company.urls', namespace='company')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

urlpatterns += [
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/accounts/urls.py
from django.urls import path
from .views import CrossAuthView, UserUpdateView, IdentificationCheckView

app_name = "accounts"
urlpatterns = [
    path('cross-auth/', CrossAuthView.as_view(), name='cross-auth-view'),
    path('user/change/', UserUpdateView.as_view(), name='user-change'),
    path('identification-check/', IdentificationCheckView.as_view(), name='identification-check'),
]

src/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "Cities"

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=3, null=True, blank=True, help_text="Short name of country like 'US', 'GB'")
    phone_code = models.CharField(max_length=5, null=True, blank=True, help_text="Phone code of country like '+92', '+1'")
    language = models.CharField(max_length=255, null=True, blank=True, help_text="Language of country like 'English', 'Urdu'")
    currency = models.CharField(max_length=255, null=True, blank=True, help_text="Currency of country like 'USD', 'PKR'")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Countries"
        ordering = ['name']


class User(AbstractUser):
    GENDER_CHOICE = (
        ('m', 'Male'),
        ('f', 'Female'),
    )

    is_customer = models.BooleanField(default=False, help_text="This account belongs to customer")
    is_company = models.BooleanField(default=False, help_text="This account belongs to Company")
    is_completed = models.BooleanField(default=False, help_text="Is user fully fully identified to access application")

    profile_image = models.ImageField(
        null=True, blank=True,
        upload_to='images/profiles/',
        verbose_name="Profile Picture", help_text="Profile image must be 150*150 in size of png, jpg or jpeg"
    )
    gender = models.CharField(max_length=1, null=False, blank=True, choices=GENDER_CHOICE)
    about = models.TextField(null=True, blank=True, help_text="Tell us something interesting about yourself")
    address = models.TextField(blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=False)
    categories = models.ManyToManyField(Category)
    phone_number = models.CharField(max_length=15, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Users"

    def __str__(self):
        if self.first_name or self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.username

    def delete(self, *args, **kwargs):
        self.profile_image.delete(save=True)
        super(User, self).delete(*args, **kwargs)

src/accounts/forms.py
from django.forms import ModelForm
from src.accounts.models import User


class UserProfileForm(ModelForm):

    class Meta:
        model = User
        fields = [
            'profile_image', 'first_name', 'last_name', 'gender',
            'phone_number', 'about', 'address', 'city', 'country', 'categories'
        ]

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from src.accounts.bll import is_account_complete
from src.accounts.forms import UserProfileForm
from src.portals.company.models import Company


@method_decorator(login_required, name='dispatch')
class CrossAuthView(View):

    def get(self, request):

        user = request.user

        # SUPER USER
        if user.is_staff:
            return redirect("/admin/")

        # NOT IDENTIFIED
        if not request.user.is_completed:
            return redirect('accounts:identification-check')

        # NOT COMPLETE
        if not is_account_complete(request.user):
            messages.warning(request, "Please complete your profile for better recommendations")
            return redirect("accounts:user-change")

        # CUSTOMER OR COMPANY
        if request.user.is_company:
            return redirect('company:dashboard')
        else:
            return redirect('customer:dashboard')


@method_decorator(login_required, name='dispatch')
class UserUpdateView(View):

    def get(self, request):
        form = UserProfileForm(instance=request.user)
        context = {'form': form}
        return render(request, template_name='accounts/user_update_form.html', context=context)

    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            messages.success(request, "Your profile updated successfully")
            form.save(commit=True)
        context = {'form': form}
        return render(request, template_name='accounts/user_update_form.html', context=context)


@method_decorator(login_required, name='dispatch')
class IdentificationCheckView(View):

    def get(self, request):

        # IS USER ALREADY IDENTIFIED
        if request.user.is_completed:
            return redirect('accounts:cross-auth-view')

        return render(request, 'accounts/identification-check.html')

    def post(self, request):

        # IF USER ALREADY IDENTIFIED
        if request.user.is_completed: return redirect('accounts:cross-auth-view')

        user_type = request.POST.get('user_type', None)

        # IF USER HAS TYPE
        if user_type is not None:
            user = request.user

            # IF USER HAS CORRECT TYPE
            if user_type == '1' or user_type == '2':
                if user_type == '1':
                    messages.success(request, "Post a job wait for applications and find a best employees.")
                    user.is_company = True
                else:
                    messages.success(request, "so you are here to find a job")
                    user.is_customer = True
                user.is_completed = True
                user.save()
                if user_type == '1':
                    Company.objects.create(user=user)
                return redirect('accounts:cross-auth-view')
            else:
                messages.error(request, "Please provide correct user type")
        else:
            messages.error(request, "Please provide user type")

        return render(request, 'accounts/identification-check.html')

src/accounts/templates/accounts/identification-check.html
{% extends 'core/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Identification Check{% endblock %}
{% block base_top_nav %}{% endblock %}

{% block dont_include_details %}

    {# HOME LINK #}
    <div class="home-btn d-none d-sm-block">
        <a href="/" class="text-dark"><i class="fas fa-home h2"></i></a>
    </div>

    <div class="my-4 pt-sm-5">

        {% include 'core/include/message.html' %}

        <div class="container">

            <!-- THIS IS UPPER AREA -->
            <div class="row justify-content-center">
                <div class="col-12 text-center">
                    <h2 class="lead mb-4" style="font-size: xx-large"><i class="fa fa-running"></i> Just One Step
                        Behind!
                    </h2>
                    <p>
                        Connect companies offering enriching internships with aspiring students seeking valuable
                        experiences. Our platform facilitates a seamless exchange, fostering a community where
                        innovation, learning, and growth converge. Join us in shaping the future of education and
                        professional development.
                    </p>
                </div>
            </div>

            <form method="post" action="">
                {% csrf_token %}

                {# FORM CONTENT -------------- #}
                <div class="row mt-4">

                    {# STUDENT #}
                    <div class="col">
                        <div class="card rounded">
                            <div class="card-body">

                                <div class="text-center">
                                    <img src="{% static 'images/logo.png' %}">
                                </div>
                            </div>
                            <div class="card-footer bg-white border-top text-center">
                                <input type="radio" value="1" name="user_type" id="user_type"
                                       class="form-check-inline"> <b class="lead">Company</b>
                            </div>

                        </div>
                    </div>

                    {# TEACHER #}
                    <div class="col">
                        <div class="card">
                            <div class="card-body">

                                <div class="text-center">
                                    <img src="{% static 'images/logo.png' %}">
                                </div>

                            </div>
                            <div class="card-footer bg-white border-top text-center">
                                <input type="radio" value="2" name="user_type" id="user_type" class="form-check-inline">
                                <b class="lead">Internee</b>
                            </div>

                        </div>
                    </div>


                </div>

                {# SUBMISSION ---------------- #}
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="text-center">
                            <button class="btn btn-lg btn-primary" type="submit">
                                <i class="fa fa-check-circle"></i>
                                Submit
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

src/accounts/templates/accounts/user_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Profile Update {% endblock %}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card p-4">
                <div class="card-body">

                    <div class="mb-2 text-center">
                        {% if form.instance.profile_image %}
                            <img src="{{ form.instance.profile_image.url }}" style='height: 150px;width: 150px;' class="rounded-circle">
                        {% else %}
                            <img src="{% static 'images/user.png' %}" style='height: 150px;width: 150px;' class="rounded-circle">
                        {% endif %}
                    </div>

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-check"></i> Submit
                        </button>
                    </form>

                </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block base_external_scripts %}
    <script>
    $(document).ready(function() {
        $('#id_gender').addClass('form-control');
        $('#id_city').addClass('form-control');
        $('#id_country').addClass('form-control');
        $('#id_categories').addClass('form-control');
    });
    </script>
{% endblock %}